# fly.toml app configuration file generated for mintoctopus-bot on 2025-08-01T21:28:51+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mintoctopus-bot'
primary_region = 'ams'

[build]

[deploy]
  strategy = 'rolling'
  release_command = "echo 'Deployment started'"

[env]
  ENVIRONMENT = 'production'
  PYTHONPATH = '/app'
  PYTHONUNBUFFERED = '1'

[[mounts]]
  source = 'bot_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

  [[services.http_checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
